name: Terraform S3 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 'latest'

    - name: Verify Terraform
      run: terraform version

    - name: Terraform Init
      run: terraform init
      working-directory: terraform-s3
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform-s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Get Bucket Name from Terraform Output
      id: bucket_name
      run: echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV
      working-directory: terraform-s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Upload Website Files to S3
      run: |
        aws s3 sync ./DevOpsZaid/ s3://$BUCKET_NAME --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Final Cleanup
      run: |
        git config --local --remove-section submodule.DevOpsZaid || true
        rm -f .gitmodules || true
